[package]
name = "quote"
version = "1.0.45"
edition = "2021"
rust-version = "1.71"
authors = ["David Tolnay <dtolnay@gmail.com>"]
build = false
description = "Quasi-quoting macro quote!(...)"
license = "MIT OR Apache-2.0"
repository = "https://github.com/dtolnay/quote"

[features]
default = ["proc-macro"]
proc-macro = ["proc-macro2/proc-macro"]

[lib]
name = "quote"
path = "src/lib.rs"

[dependencies.proc-macro2]
version = "1.0.80"
default-features = false
